Repository seung-lab/cloud-volume, pull requests merged in 2018-12, with the labels that each got.

#165 feat(storage): Batch requests for GCS files_exist()
  cloudvolume/lib.py
  cloudvolume/storage.py
Labels: performance

#168 fix: multiprocess upload crashes on thin non-aligned images
  cloudvolume/txrx.py
  test/test_cloudvolume.py
Labels: bug

#169 allow reestablishing viewer server in the same python session
  cloudvolume/viewer.py
  cloudvolume/volumecutout.py
Labels: feature

#173 fix: close requests streams
  ChangeLog
  cloudvolume/connectionpools.py
  cloudvolume/exceptions.py
  cloudvolume/lib.py
  cloudvolume/storage.py
Labels: bug
