Repository seung-lab/cloud-volume, pull requests merged in 2018-04, with the labels that each got.

#91 Changing the docs a bit
  README.md
Labels: documentation

#86 feat: preserve option for fush_cache + flush_cache_region
  README.md
  cloudvolume/__init__.py
  cloudvolume/cacheservice.py
  cloudvolume/cloudvolume.py
  cloudvolume/lib.py
  cloudvolume/storage.py
  cloudvolume/volumecutout.py
  test/test_cloudvolume.py
Labels: feature

#92 feat: Added non-aligned chunk uploads.
  AUTHORS
  ChangeLog
  cloudvolume/__init__.py
  cloudvolume/cacheservice.py
  cloudvolume/cloudvolume.py
  cloudvolume/lib.py
  cloudvolume/storage.py
  cloudvolume/txrx.py
  test/test_cloudvolume.py
Labels: feature

#97 feat: shared memory emulation using the filesystem for OSX
  cloudvolume/sharedmemory.py
  cloudvolume/txrx.py
  test/test_sharedmemory.py
Labels: bug, feature

#98 feat: parallel uploads
  ChangeLog
  cloudvolume/sharedmemory.py
  cloudvolume/txrx.py
  test/test_cloudvolume.py
  test/test_sharedmemory.py
Labels: feature

#99 perf: use fortran order internally in numpy arrays
  ChangeLog
  cloudvolume/chunks.py
  cloudvolume/sharedmemory.py
  cloudvolume/txrx.py
  cloudvolume/volumecutout.py
Labels: performance

#101 feat: upload from shared memory
  cloudvolume/cloudvolume.py
  cloudvolume/sharedmemory.py
  cloudvolume/txrx.py
  test/test_cloudvolume.py
  test/test_sharedmemory.py
Labels: feature

#104 fix: tqdm race condition "AttributeError: 'tqdm' object has no attrib…
  requirements.txt
Labels: bug
