Repository seung-lab/cloud-volume, pull requests merged in 2019-10, with the labels that each got.

#269 feat: Add "fuse" to graphene meshes
  cloudvolume/datasource/graphene/mesh.py
  cloudvolume/datasource/precomputed/mesh.py
  cloudvolume/mesh.py
Labels: bug, feature, redesign

#270 feat: add redirection feature to info files
  README.md
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/__init__.py
  cloudvolume/datasource/boss/image.py
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/mesh.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/skeleton/__init__.py
  cloudvolume/datasource/precomputed/skeleton/sharded.py
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
  cloudvolume/exceptions.py
  cloudvolume/frontends/precomputed.py
  cloudvolume/paths.py
  test/test_cloudvolume.py
Labels: feature

#272 fix: actually del cls
  cloudvolume/cloudvolume.py
Labels: bug

#274 fix: use OS+protocol aware join command for meshes and skeletons
  cloudvolume/datasource/precomputed/image/tx.py
  cloudvolume/datasource/precomputed/mesh.py
Labels: bug

#271 sets ACL by default for s3 interface
  cloudvolume/storage/storage_interfaces.py
Labels: feature

#277 feat: read skeleton spatial index + sharded format writer
  README.md
  cloudvolume/cacheservice.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/datasource/precomputed/skeleton/metadata.py
  cloudvolume/datasource/precomputed/skeleton/sharded.py
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
  cloudvolume/datasource/precomputed/spatial_index.py
  cloudvolume/exceptions.py
  cloudvolume/lib.py
  test/test_skeletons.py
Labels: feature

#278 feat: add brotli compression option
  README.md
  cloudvolume/cacheservice.py
  cloudvolume/cloudvolume.py
  cloudvolume/compression.py
  cloudvolume/datasource/boss/__init__.py
  cloudvolume/datasource/graphene/__init__.py
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/tx.py
  cloudvolume/datasource/precomputed/skeleton/__init__.py
  cloudvolume/exceptions.py
  cloudvolume/lib.py
  cloudvolume/storage/storage.py
  cloudvolume/storage/storage_interfaces.py
  requirements.txt
  test/test_cloudvolume.py
  test/test_compression.py
  test/test_lib.py
  test/test_storage.py
Labels: feature
