Repository seung-lab/cloud-volume, pull requests merged in 2019-06, with the labels that each got.

#223 perf: omit a network request when creating a GCS connection
  cloudvolume/connectionpools.py
Labels: performance

#212 feat: delete black uploads flag
  README.md
  cloudvolume/cloudvolume.py
  cloudvolume/storage.py
  cloudvolume/txrx.py
  test/layer_harness.py
  test/test_cloudvolume.py
Labels: feature

#228 refactor: split up Storage, add components of Green threads
  README.md
  cloudvolume/cloudvolume.py
  cloudvolume/scheduler.py
  cloudvolume/storage.py
  cloudvolume/storage/__init__.py
  cloudvolume/storage/storage.py
  cloudvolume/storage/storage_interfaces.py
  cloudvolume/threaded_queue.py
  cloudvolume/txrx.py
  cloudvolume/volumecutout.py
Labels: feature, refactor

#231 fix: microviewer installation, pixel value update, scroll direction
  AUTHORS
  MANIFEST.in
  cloudvolume/__init__.py
  cloudvolume/microviewer/__init__.py
  cloudvolume/microviewer/datacube.js
  cloudvolume/microviewer/favicon.ico
  cloudvolume/microviewer/index.html
  cloudvolume/microviewer/jquery-3.3.1.js
  cloudvolume/volumecutout.py
  setup.py
Labels: bug
