Repository seung-lab/cloud-volume, pull requests merged in 2019-12, with the labels that each got.

#296 fix(ShardReader): only scan labels in minishard_index
  cloudvolume/datasource/precomputed/sharding.py
Labels: bug

#292 fix: EmptyVolumeException w/ non_aligned_writes
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/tx.py
  test/test_cloudvolume.py
  test/test_storage.py
Labels: bug

#291 install: requests/urllib supports brotli
  cloudvolume/storage/storage_interfaces.py
  requirements.txt
Labels: refactor

#298 perf: cache shard and minishard indices
  cloudvolume/datasource/precomputed/sharding.py
  requirements.txt
Labels: bug, performance

#300 changing spelling of isAlive>is_alive
  test/test_threadedqueue.py
Labels: refactor

#297 fix+test: Graphene mesh tests & fixes subclassing
  cloudvolume/datasource/graphene/mesh.py
  cloudvolume/datasource/graphene/metadata.py
  setup.py
  test/test_cv/mesh_mip_2_draco_sv16/185457065798402451:0:9344-9472_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186015583345574368:0:9472-9600_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186015583345574392:0:9472-9600_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186015617705312523:0:9472-9600_7040-7168_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186015617705312554:0:9472-9600_7040-7168_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186015617705312679:0:9472-9600_7040-7168_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186019981392085528:0:9472-9600_7168-7296_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186020015751823467:0:9472-9600_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186020015751823580:0:9472-9600_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995573:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995633:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995649:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995658:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995665:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578533298995668:0:9600-9728_7040-7168_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186578567658733578:0:9600-9728_7040-7168_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186582931345506347:0:9600-9728_7168-7296_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186582931345506398:0:9600-9728_7168-7296_768-896
  test/test_cv/mesh_mip_2_draco_sv16/186582965705244694:0:9600-9728_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186582965705244822:0:9600-9728_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/186582965705244902:0:9600-9728_7168-7296_896-1024
  test/test_cv/mesh_mip_2_draco_sv16/648518346349515986:0
  test/test_cv/mesh_mip_2_err_40_sv16/648518346349515986:0
  test/test_cv/mesh_mip_2_err_40_sv16/9185457065798402451:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186015583345574368:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186015583345574392:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186015617705312523:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186015617705312554:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186015617705312679:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186019981392085528:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186020015751823467:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186020015751823580:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186020015751823722:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995573:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995633:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995649:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995658:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995665:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578533298995668:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186578567658733578:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186582931345506347:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186582931345506398:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186582965705244694:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186582965705244822:0.gz
  test/test_cv/mesh_mip_2_err_40_sv16/9186582965705244902:0.gz
  test/test_graphene.py
Labels: bug, testing

#289 fix: accurate mip level and voxel offset accomodation for vertex deduplication
  cloudvolume/__init__.py
  cloudvolume/datasource/precomputed/mesh/metadata.py
  cloudvolume/datasource/precomputed/mesh/unsharded.py
  cloudvolume/mesh.py
  test/test_cloudvolume.py
  test/test_meshing.py
Labels: feature

#306 redesign: cv.shape returns a tuple + cv.ndim (BREAKING)
  cloudvolume/frontends/precomputed.py
Labels: feature, redesign
