Repository seung-lab/cloud-volume, pull requests merged in 2019-08, with the labels that each got.

#255 chore: make pytest optional with [test] dependency
  .travis.yml
  requirements.txt
  setup.py
Labels: installation, refactor, testing

#257 feat(PrecomputedSkeleton): optionally return indices for paths
  cloudvolume/datasource/precomputed/skeleton.py
Labels: feature

#259 fix: allow ports in bucket paths
  cloudvolume/paths.py
  test/test_paths.py
Labels: bug

#239 feat: Read Sharded Precomputed Skeletons
  .travis.yml
  README.md
  cloudvolume/__init__.py
  cloudvolume/cacheservice.py
  cloudvolume/datasource/precomputed/common.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/mmh3.py
  cloudvolume/datasource/precomputed/rx.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/datasource/precomputed/skeleton/__init__.py
  cloudvolume/datasource/precomputed/skeleton/metadata.py
  cloudvolume/datasource/precomputed/skeleton/sharded.py
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
  cloudvolume/exceptions.py
  cloudvolume/paths.py
  cloudvolume/skeleton.py
  cloudvolume/storage/storage.py
  cloudvolume/storage/storage_interfaces.py
  requirements.txt
  test/test_paths.py
  test/test_sharding.py
  test/test_skeletons.py
Labels: feature, performance, refactor

#260 fix: treat 403 like 404 for HTTPS interface
  cloudvolume/storage/storage_interfaces.py
Labels: bug

#254 graphene tests and cutout bug fix
  .gitignore
  .travis.yml
  cloudvolume/datasource/graphene/__init__.py
  cloudvolume/datasource/graphene/mesh.py
  cloudvolume/datasource/graphene/metadata.py
  cloudvolume/datasource/precomputed/mesh.py
  cloudvolume/frontends/graphene.py
  cloudvolume/frontends/precomputed.py
  cloudvolume/lib.py
  cloudvolume/mesh.py
  requirements.txt
  setup.py
  test/test_graphene.py
Labels: bug

#261 feat: support for chunked graph server authentication
  README.md
  cloudvolume/datasource/graphene/mesh.py
  cloudvolume/datasource/graphene/metadata.py
  cloudvolume/frontends/graphene.py
  cloudvolume/secrets.py
Labels: feature

#263 feat: reading sharded images
  cloudvolume/cacheservice.py
  cloudvolume/datasource/precomputed/common.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/common.py
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/image/tx.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/datasource/precomputed/skeleton/metadata.py
  cloudvolume/datasource/precomputed/skeleton/sharded.py
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
  cloudvolume/lib.py
  test/test_cloudvolume.py
  test/test_sharding.py
  test/test_skeletons.py
Labels: feature
