Repository seung-lab/cloud-volume, pull requests merged in 2019-07, with the labels that each got.

#230 feat+refactor: break up cloudvolume into modules + goodies
  README.md
  cloudvolume/__init__.py
  cloudvolume/cacheservice.py
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/__init__.py
  cloudvolume/datasource/boss/__init__.py
  cloudvolume/datasource/boss/image.py
  cloudvolume/datasource/boss/metadata.py
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/datasource/precomputed/common.py
  cloudvolume/datasource/precomputed/image.py
  cloudvolume/datasource/precomputed/mesh.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/rx.py
  cloudvolume/datasource/precomputed/skeleton.py
  cloudvolume/datasource/precomputed/tx.py
  cloudvolume/lib.py
  cloudvolume/meshservice.py
  cloudvolume/sharedmemory.py
  cloudvolume/storage/storage.py
  cloudvolume/txrx.py
  cloudvolume/volumecutout.py
  requirements.txt
  test/test_cloudvolume.py
  test/test_sharedmemory.py
  test/test_skeletons.py
Labels: feature, performance, refactor

#234 fix: only install psutil and posix_ipc on non-windows platforms
  MANIFEST.in
  README.md
  cloudvolume/cacheservice.py
  cloudvolume/datasource/precomputed/common.py
  cloudvolume/datasource/precomputed/image.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/rx.py
  cloudvolume/lib.py
  cloudvolume/secrets.py
  cloudvolume/sharedmemory.py
  cloudvolume/storage/storage.py
  cloudvolume/storage/storage_interfaces.py
  requirements.txt
  setup.cfg
  setup.py
  setversion.py
  test/test_lib.py
  test/test_sharedmemory.py
Labels: installation

#242 adding test for use_https and fixing replace call
  cloudvolume/cloudvolume.py
  test/test_cloudvolume.py
Labels: bug

#243 feat: add PrecomputedSkeleton.remove_disconnected_vertices
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/precomputed/skeleton.py
  test/test_skeletons.py
Labels: feature

#244 install: skip DracoPy for Python2.7
  README.md
  setup.py
Labels: installation

#250 fix: correct ExtractedPath import for web server viewer
  cloudvolume/server.py
Labels: bug

#248 fix: added use_https to graphene metadata service
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/graphene/__init__.py
  cloudvolume/datasource/graphene/metadata.py
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/paths.py
Labels: bug
