Repository seung-lab/cloud-volume, pull requests merged in 2019-02, with the labels that each got.

#195 add support for default region
  cloudvolume/secrets.py
Labels: feature

#188 Add from_numpy Function to Automatically Construct a Precomputed Volume
  cloudvolume/cloudvolume.py
  cloudvolume/lib.py
  test/test_cloudvolume.py
  test/test_lib.py
Labels: feature

#196 chore: fpzip 1.1.3 compatibility
  cloudvolume/chunks.py
  requirements.txt
Labels: bug, performance, refactor

#197 fix from numpy function with multiple mip levels
  cloudvolume/cloudvolume.py
  test/test_cloudvolume.py
Labels: bug

#200 add boolean and use floating abstract dtype
  cloudvolume/cloudvolume.py
Labels: bug

#202 perf: 1.5-2x faster CloudVolume on Google Cloud Storage
  cloudvolume/storage.py
Labels: performance
