Repository seung-lab/cloud-volume, pull requests merged in 2020-08, with the labels that each got.

#374 redesign(graphene): use synthetic manifests for fetching meshes
  cloudvolume/datasource/graphene/mesh/sharded.py
  cloudvolume/datasource/graphene/mesh/unsharded.py
Labels: graphene, performance, redesign

#355 adding smart graphene multi-level mesh stitching
  cloudvolume/datasource/graphene/mesh/sharded.py
  cloudvolume/frontends/graphene.py
  cloudvolume/mesh.py
Labels: feature

#378 perf: skip compression/decompression cycle for caching
  cloudvolume/cacheservice.py
  cloudvolume/compression.py
  cloudvolume/exceptions.py
  cloudvolume/lib.py
  requirements.txt
  test/test_cloudvolume.py
  test/test_compression.py
  test/test_meshing.py
Labels: images, meshes, performance, skeletons

#379 perf(rx): faster caching by taking advantage of raw downloads
  cloudvolume/cacheservice.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/image/tx.py
  requirements.txt
  test/test_cloudvolume.py
Labels: images, performance

#383 BREAKING: Drop official support for Python 2.7
  .travis.yml
  README.md
  setup.py
Labels: documentation, installation, redesign

#386 fix(graphene): update leaves call for api v1
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/frontends/graphene.py
Labels: bug

#388 fix: ensure segid assigned to meshes
  cloudvolume/datasource/graphene/mesh/sharded.py
  cloudvolume/mesh.py
Labels: bug

#390 fix(graphene): dynamic mesh computed filename didn't account for layer
  cloudvolume/datasource/graphene/mesh/unsharded.py
Labels: bug
