Repository seung-lab/cloud-volume, pull requests merged in 2020-07, with the labels that each got.

#356 fix: default to 'raw' for shard encodings
  cloudvolume/datasource/precomputed/sharding.py
Labels: bug

#353 refactor: exchange Storage for CloudFiles
  cloudvolume/cacheservice.py
  cloudvolume/datasource/graphene/mesh/sharded.py
  cloudvolume/datasource/graphene/mesh/unsharded.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/image/tx.py
  cloudvolume/datasource/precomputed/mesh/multilod.py
  cloudvolume/datasource/precomputed/mesh/unsharded.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
  cloudvolume/datasource/precomputed/spatial_index.py
  cloudvolume/scheduler.py
  cloudvolume/server.py
  cloudvolume/skeleton.py
  requirements.txt
  test/test_cloudvolume.py
Labels: refactor

#359 feat(PrecomputedImage): adds has_data(mip) call
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/lib.py
  test/test_cloudvolume.py
Labels: feature

#358 feat(PrecomputedImage): add make_shard function
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/rx.py
  test/test_sharding.py
Labels: feature

#360 fix(precomputed): makeshard cutouts relative to provided image
  cloudvolume/datasource/precomputed/image/__init__.py
Labels: bug

#362 fix: special logic for handling slices
  cloudvolume/frontends/precomputed.py
  cloudvolume/lib.py
  test/test_lib.py
Labels: bug

#366 Fix: get_meshes_on_bypass
  cloudvolume/datasource/graphene/mesh/sharded.py
Labels: bug

#364 feat: add agglomerate mode for graphene
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/graphene/__init__.py
  cloudvolume/datasource/graphene/metadata.py
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/frontends/graphene.py
Labels: feature

#370 fix: incompatibility between inital and dynamic meshes
  cloudvolume/datasource/graphene/mesh/sharded.py
Labels: bug
