Repository seung-lab/cloud-volume, pull requests merged in 2020-09, with the labels that each got.

#392 perf: use simplejpeg for JPEG encoding/decoding
  cloudvolume/chunks.py
  requirements.txt
  test/test_chunks.py
Labels: images, performance, refactor

#393 test(graphene): add tests for meshes based on real data
  test/test_cv/sharded_info.json
  test/test_graphene.py
Labels: graphene, meshes, testing

#400 fix(graphene): if timestamp is None, to_unix_time breaks
  cloudvolume/frontends/graphene.py
Labels: bug, graphene

#399 fix(windows,paths): non-file windows parsing was broken
  cloudvolume/paths.py
  test/test_paths.py
Labels: Windows, bug, testing

#402 fix(sharded,mesh): pass progress to CloudFiles
  cloudvolume/datasource/precomputed/mesh/multilod.py
Labels: bug

#401 fix(use_https): redirects respect the use_https flag
  cloudvolume/datasource/precomputed/__init__.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/paths.py
Labels: bug

#405 chore(Windows): install dracopy on windows
  requirements.txt
  setup.py
Labels: Windows, feature, installation, meshes

#396 perf(sharding): compressed morton code and gridpoints
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/common.py
  cloudvolume/datasource/precomputed/image/rx.py
  test/test_sharding.py
Labels: images, performance, refactor, sharding

#410 refactor(compressed_segmentation): use updated 2.0.0 package
  cloudvolume/chunks.py
  requirements.txt
Labels: bug, refactor

#403 fixing level=2 for bounding box queries
  cloudvolume/datasource/graphene/mesh/sharded.py
Labels: redesign

#413 Missing 'import re' in mesh.py.
  cloudvolume/mesh.py
Labels: bug
