Repository seung-lab/cloud-volume, pull requests merged in 2020-04, with the labels that each got.

#318 feat: making sharded mesh readers for graphene, added decoder for labels
  README.md
  cloudvolume/cacheservice.py
  cloudvolume/datasource/graphene/mesh/__init__.py
  cloudvolume/datasource/graphene/mesh/metadata.py
  cloudvolume/datasource/graphene/mesh/sharded.py
  cloudvolume/datasource/graphene/mesh/unsharded.py
  cloudvolume/datasource/graphene/metadata.py
  cloudvolume/datasource/graphene/sharding.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/frontends/graphene.py
  setup.py
  test/test_graphene.py
Labels: feature

#324 feat: add image write locking per mip level
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/exceptions.py
  test/test_cloudvolume.py
Labels: feature

#328 refactor: drop pylru for custom version
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/lru.py
  requirements.txt
  test/test_lru.py
Labels: refactor

#327 feat: add ShardReader.list_labels
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/lib.py
  cloudvolume/storage/storage.py
  test/test_skeletons.py
Labels: feature

#330 fix: support fill_missing for sharded images
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/exceptions.py
Labels: bug

#331 fix: pass arguments to super more accurately
  cloudvolume/datasource/graphene/mesh/sharded.py
Labels: bug

#332 feat: add mesh_dir and skel_dir arguments to CloudVolume
  cloudvolume/cloudvolume.py
  cloudvolume/datasource/graphene/__init__.py
  cloudvolume/datasource/graphene/sharding.py
  cloudvolume/datasource/precomputed/__init__.py
Labels: bug, feature

#334 perf: instant fs based shared memory files + use spare file capability
  cloudvolume/sharedmemory.py
Labels: performance, redesign

#323 Add range read request to graphene and new properties to graphene metadata
  cloudvolume/frontends/graphene.py
Labels: feature

#336 feat(ShardReader): add disassemble_shard to recover the input dict
  cloudvolume/datasource/precomputed/sharding.py
  test/test_skeletons.py
Labels: feature, refactor

#335 feat(microviewer): add segmentation toggle to plain segmentation
  cloudvolume/microviewer/__init__.py
  cloudvolume/microviewer/datacube.js
  cloudvolume/microviewer/index.html
Labels: feature
