Repository seung-lab/cloud-volume, pull requests merged in 2021-07, with the labels that each got.

#484 allowing translation for multi-lod-mesh
  cloudvolume/datasource/precomputed/mesh/multilod.py
  cloudvolume/datasource/precomputed/mesh/unsharded.py
  test/test_meshing.py
  test/test_precomputed_multilod.py
Labels: feature

#488 feat(Bbox): allow negative and tuple or array amt to grow bounding box
  cloudvolume/lib.py
  test/test_lib.py
Labels: feature, testing

#487 fix: make parallel image IO more robust
  cloudvolume/datasource/precomputed/image/common.py
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/image/tx.py
  cloudvolume/lib.py
  cloudvolume/scheduler.py
  cloudvolume/sharedmemory.py
  cloudvolume/storage/storage_interfaces.py
  requirements.txt
Labels: bug, redesign
