Repository seung-lab/cloud-volume, pull requests merged in 2021-06, with the labels that each got.

#476 fix(spatial_index): correct calculation of file paths
  cloudvolume/datasource/precomputed/spatial_index.py
  cloudvolume/lib.py
  test/test_lib.py
Labels: bug

#478 fix(image shard): morton codes not handling single dimensions
  cloudvolume/datasource/precomputed/image/common.py
  test/test_sharding.py
Labels: bug

#421 feat: add compresso encoding
  README.md
  cloudvolume/chunks.py
  cloudvolume/datasource/precomputed/common.py
  requirements.txt
  test/test_chunks.py
Labels: feature

#483 make max_mip inclusive in generating info file
  cloudvolume/datasource/precomputed/metadata.py
Labels: redesign

#482 fix: update morton coding
  cloudvolume/datasource/precomputed/image/common.py
  test/test_sharding.py
Labels: bug, images, sharding, testing
