Repository seung-lab/cloud-volume, pull requests merged in 2022-05, with the labels that each got.

#539 Respect compression settings for skeleton uploads.
  cloudvolume/datasource/precomputed/skeleton/unsharded.py
Labels: bug

#541 fix+feat: Multi-Resolution Mesh Encoding
  cloudvolume/datasource/precomputed/mesh/multilod.py
Labels: bug, feature

#532 feat: cv.image.download_files
  README.md
  cloudvolume/chunks.py
  cloudvolume/datasource/precomputed/common.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/rx.py
  cloudvolume/datasource/precomputed/sharding.py
  cloudvolume/frontends/graphene.py
  cloudvolume/frontends/precomputed.py
  test/test_cloudvolume.py
Labels: feature, images
