Repository seung-lab/cloud-volume, pull requests merged in 2024-07, with the labels that each got.

#619 feat: Add "unit" to Bbox + accept physical Bbox in CV image functions
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/frontends/precomputed.py
  cloudvolume/lib.py
  test/test_cloudvolume.py
  test/test_lib.py
Labels: feature

#615 feat: add support for jpegxl image compression
  README.md
  cloudvolume/chunks.py
  cloudvolume/datasource/precomputed/image/__init__.py
  cloudvolume/datasource/precomputed/image/xfer.py
  cloudvolume/datasource/precomputed/metadata.py
  cloudvolume/exceptions.py
  cloudvolume/frontends/precomputed.py
  cloudvolume/py_compressed_segmentation.py
  cloudvolume/types.py
  requirements.txt
  setup.py
  test/test_chunks.py
  test/test_cloudvolume.py
Labels: feature, images

#623 Fix Callable type annotation
  cloudvolume/chunks.py
Labels: bug

#624 Fixes for lib.save_image
  cloudvolume/lib.py
  setup.py
Labels: bug
